/* 
INSTALL: If you are using this data for your own site or profile make sure to change set you own data.

The objects below can be used as a starting point. Delete the original data and start from these.

const headerBlockData = {
    description: "Your Description",
    linkedinprofile: "Your Linkedin Profile URL",
    lastupdatedat: "28 Sep 2020"
};

const skillFilters = [
    { displayname: "Your Filter Name", filter: "ID of on of your skills"},
];

const skillsHistory = [
    {
        name: "C#/.NET/.NET Core",
        id: ".net",
        colour: "a27bdc",
        history: [
            { period: 20203, usage: "primary" },
        ]
    }
];
*/

const headerBlockData = {
    description: "Skills History for Aaron Clauson",
    linkedinprofile: "https://www.linkedin.com/in/aaron-clauson-81770144/",
    lastupdatedat: "28 Sep 2020"
};

const skillFilters = [
    { displayname: ".NET", filter: ".net"},
    { displayname: "Real-time Communications", filter: "rtc"},
    { displayname: "Web Development", filter: "webdev"},
    { displayname: "Database", filter: "rdbms"},
    { displayname: "Other", filter: "other"},
];

const skillsHistory = [
    {
        name: "C#/.NET/.NET Core",
        id: ".net",
        colour: "a27bdc",
        history: [
            { period: 20203, usage: "primary" },
            { period: 20202, usage: "primary" },
            { period: 20201, usage: "primary" },
            { period: 20194, usage: "primary" },
            { period: 20193, usage: "occasional" },
            { period: 20192, usage: "occasional" },
            { period: 20191, usage: "occasional" },
            { period: 20184, usage: "occasional" },
            { period: 20183, usage: "occasional" },
            { period: 20182, usage: "occasional" },
            { period: 20181, usage: "occasional" },
            { period: 20174, usage: "occasional" },
            { period: 20173, usage: "primary" },
            { period: 20172, usage: "primary" },
            { period: 20171, usage: "primary" },
            { period: 20164, usage: "primary" },
            { period: 20163, usage: "primary" },
            { period: 20162, usage: "primary" },
            { period: 20161, usage: "primary" },
            { period: 20154, usage: "primary" },
            { period: 20153, usage: "primary" },
            { period: 20152, usage: "primary" },
            { period: 20151, usage: "primary" },
            { period: 20144, usage: "primary" },
            { period: 20143, usage: "primary" },
            { period: 20142, usage: "primary" },
            { period: 20141, usage: "primary" },
            { period: 20134, usage: "primary" },
            { period: 20133, usage: "primary" },
            { period: 20132, usage: "primary" },
            { period: 20131, usage: "primary" },
            { period: 20124, usage: "primary" },
            { period: 20123, usage: "primary" },
            { period: 20122, usage: "primary" },
            { period: 20121, usage: "primary" },
            { period: 20114, usage: "primary" },
            { period: 20113, usage: "primary" },
            { period: 20112, usage: "primary" },
            { period: 20111, usage: "primary" },
            { period: 20104, usage: "primary" },
            { period: 20103, usage: "primary" },
            { period: 20102, usage: "primary" },
            { period: 20101, usage: "primary" },
            { period: 20094, usage: "primary" },
            { period: 20093, usage: "primary" },
            { period: 20092, usage: "primary" },
            { period: 20091, usage: "primary" },
            { period: 20084, usage: "regular" },
            { period: 20083, usage: "regular" },
            { period: 20082, usage: "occasional" },
            { period: 20081, usage: "primary" },
            { period: 20074, usage: "primary" },
            { period: 20073, usage: "primary" },
            { period: 20072, usage: "primary" },
            { period: 20071, usage: "primary" },
            { period: 20064, usage: "primary" },
            { period: 20063, usage: "primary" },
            { period: 20062, usage: "primary" },
            { period: 20061, usage: "primary" },
            { period: 20054, usage: "primary" },
            { period: 20053, usage: "primary" },
            { period: 20052, usage: "primary" },
            { period: 20051, usage: "primary" },
            { period: 20044, usage: "primary" },
            { period: 20043, usage: "primary" },
            { period: 20042, usage: "primary" },
            { period: 20041, usage: "primary" },
            { period: 20034, usage: "primary" },
            { period: 20033, usage: "primary" },
            { period: 20032, usage: "primary" },
            { period: 20031, usage: "primary" },
            { period: 20024, usage: "primary" },
            { period: 20023, usage: "primary" },
            { period: 20022, usage: "primary" },
            { period: 20021, usage: "primary" },
            { period: 20014, usage: "occasional" },
        ],
    },
    {
        name: ".NET Framework 0.9/1.x/2.x/3.x/4.x",
        parentid: [".net"],
        colour: "9400D3",
        history: [
            { period: 20203, usage: "occasional" },
            { period: 20202, usage: "occasional" },
            { period: 20201, usage: "occasional" },
            { period: 20194, usage: "occasional" },
            { period: 20193, usage: "occasional" },
            { period: 20192, usage: "occasional" },
            { period: 20191, usage: "occasional" },
            { period: 20184, usage: "occasional" },
            { period: 20183, usage: "occasional" },
            { period: 20182, usage: "occasional" },
            { period: 20181, usage: "occasional" },
            { period: 20174, usage: "occasional" },
            { period: 20173, usage: "primary" },
            { period: 20172, usage: "primary" },
            { period: 20171, usage: "primary" },
            { period: 20164, usage: "primary" },
            { period: 20163, usage: "primary" },
            { period: 20162, usage: "primary" },
            { period: 20161, usage: "primary" },
            { period: 20154, usage: "primary" },
            { period: 20153, usage: "primary" },
            { period: 20152, usage: "primary" },
            { period: 20151, usage: "primary" },
            { period: 20144, usage: "primary" },
            { period: 20143, usage: "primary" },
            { period: 20142, usage: "primary" },
            { period: 20141, usage: "primary" },
            { period: 20134, usage: "primary" },
            { period: 20133, usage: "primary" },
            { period: 20132, usage: "primary" },
            { period: 20131, usage: "primary" },
            { period: 20124, usage: "primary" },
            { period: 20123, usage: "primary" },
            { period: 20122, usage: "primary" },
            { period: 20121, usage: "primary" },
            { period: 20114, usage: "primary" },
            { period: 20113, usage: "primary" },
            { period: 20112, usage: "primary" },
            { period: 20111, usage: "primary" },
            { period: 20104, usage: "primary" },
            { period: 20103, usage: "primary" },
            { period: 20102, usage: "primary" },
            { period: 20101, usage: "primary" },
            { period: 20094, usage: "primary" },
            { period: 20093, usage: "primary" },
            { period: 20092, usage: "primary" },
            { period: 20091, usage: "primary" },
            { period: 20084, usage: "regular" },
            { period: 20083, usage: "regular" },
            { period: 20082, usage: "occasional" },
            { period: 20081, usage: "primary" },
            { period: 20074, usage: "primary" },
            { period: 20073, usage: "primary" },
            { period: 20072, usage: "primary" },
            { period: 20071, usage: "primary" },
            { period: 20064, usage: "primary" },
            { period: 20063, usage: "primary" },
            { period: 20062, usage: "primary" },
            { period: 20061, usage: "primary" },
            { period: 20054, usage: "primary" },
            { period: 20053, usage: "primary" },
            { period: 20052, usage: "primary" },
            { period: 20051, usage: "primary" },
            { period: 20044, usage: "primary" },
            { period: 20043, usage: "primary" },
            { period: 20042, usage: "primary" },
            { period: 20041, usage: "primary" },
            { period: 20034, usage: "primary" },
            { period: 20033, usage: "primary" },
            { period: 20032, usage: "primary" },
            { period: 20031, usage: "primary" },
            { period: 20024, usage: "primary" },
            { period: 20023, usage: "primary" },
            { period: 20022, usage: "primary" },
            { period: 20021, usage: "primary" },
            { period: 20014, usage: "occasional" },
        ],
    },
    {
        name: ".NET Core 3.x",
        parentid: [".net"],
        colour: "9932CC",
        history: [
            { period: 20203, usage: "primary" },
            { period: 20202, usage: "primary" },
            { period: 20201, usage: "primary" },
            { period: 20194, usage: "primary" }
        ]
    },

    {
        name: "ASP.NET",
        colour: "D8BFD8",
        parentid: [".net", "webdev"],
        history: [
            { period: 20173, usage: "primary" },
            { period: 20172, usage: "primary" },
            { period: 20171, usage: "primary" },
            { period: 20164, usage: "primary" },
            { period: 20163, usage: "primary" },
            { period: 20162, usage: "primary" },
            { period: 20161, usage: "primary" },
            { period: 20154, usage: "primary" },
            { period: 20153, usage: "primary" },
            { period: 20152, usage: "primary" },
            { period: 20151, usage: "primary" },
            { period: 20144, usage: "primary" },
            { period: 20143, usage: "primary" },
            { period: 20142, usage: "primary" },
            { period: 20141, usage: "primary" },
            { period: 20134, usage: "primary" },
            { period: 20133, usage: "primary" },
            { period: 20132, usage: "primary" },
            { period: 20131, usage: "primary" },
            { period: 20124, usage: "primary" },
            { period: 20123, usage: "primary" },
            { period: 20122, usage: "regular" },
            { period: 20121, usage: "regular" },
            { period: 20114, usage: "occasional" },
            { period: 20113, usage: "primary" },
            { period: 20112, usage: "primary" },
            { period: 20111, usage: "primary" },
            { period: 20104, usage: "primary" },
            { period: 20103, usage: "primary" },
            { period: 20081, usage: "primary" },
            { period: 20074, usage: "primary" },
            { period: 20073, usage: "primary" },
            { period: 20072, usage: "primary" },
            { period: 20071, usage: "primary" },
            { period: 20064, usage: "primary" },
            { period: 20063, usage: "primary" },
            { period: 20062, usage: "primary" },
            { period: 20061, usage: "primary" },
            { period: 20054, usage: "primary" },
            { period: 20053, usage: "primary" },
            { period: 20052, usage: "primary" }
        ]
    },
    {
        name: "ASP.NET MVC",
        colour: "DDA0DD",
        parentid: [".net", "webdev"],
        history: [
            { period: 20173, usage: "primary" },
            { period: 20172, usage: "primary" },
            { period: 20171, usage: "primary" },
            { period: 20164, usage: "primary" },
            { period: 20163, usage: "primary" },
            { period: 20162, usage: "primary" },
            { period: 20161, usage: "primary" },
            { period: 20154, usage: "primary" },
            { period: 20153, usage: "primary" },
            { period: 20152, usage: "primary" },
            { period: 20151, usage: "primary" },
            { period: 20144, usage: "primary" },
            { period: 20143, usage: "primary" },
            { period: 20142, usage: "primary" },
            { period: 20141, usage: "primary" },
            { period: 20134, usage: "primary" },
            { period: 20133, usage: "primary" },
            { period: 20132, usage: "primary" },
            { period: 20131, usage: "primary" },
            { period: 20124, usage: "primary" },
            { period: 20123, usage: "primary" },
            { period: 20122, usage: "regular" },
            { period: 20121, usage: "regular" },
            { period: 20114, usage: "occasional" },
            { period: 20113, usage: "primary" },
            { period: 20112, usage: "primary" },
            { period: 20111, usage: "primary" },
            { period: 20104, usage: "primary" },
            { period: 20103, usage: "primary" },
        ]
    },
    {
        name: "ASP.NET Web API",
        colour: "EE82EE",
        parentid: [".net", "webdev"],
        history: [
            { period: 20173, usage: "primary" },
            { period: 20172, usage: "primary" },
            { period: 20171, usage: "primary" },
            { period: 20164, usage: "primary" },
            { period: 20163, usage: "primary" },
            { period: 20162, usage: "primary" },
            { period: 20161, usage: "primary" },
            { period: 20154, usage: "primary" },
            { period: 20153, usage: "primary" },
            { period: 20152, usage: "primary" },
            { period: 20151, usage: "primary" },
            { period: 20144, usage: "primary" },
            { period: 20143, usage: "primary" },
            { period: 20142, usage: "primary" },
            { period: 20141, usage: "primary" },
            { period: 20134, usage: "primary" },
            { period: 20133, usage: "primary" },
            { period: 20132, usage: "primary" },
            { period: 20131, usage: "primary" },
            { period: 20124, usage: "primary" },
            { period: 20123, usage: "primary" },
            { period: 20122, usage: "regular" },
        ]
    },
    {
        name: "ASP.NET Core",
        colour: "DA70D6",
        parentid: [".net", "webdev"],
        history: [
            { period: 20203, usage: "occasional" },
            { period: 20202, usage: "occasional" },
            { period: 20201, usage: "occasional" },
            { period: 20194, usage: "occasional" },
        ]
    },
    {
        name: "ASP.NET MVC",
        colour: "FF00FF",
        parentid: [".net", "webdev"],
        history: [
            { period: 20203, usage: "occasional" },
            { period: 20202, usage: "occasional" },
            { period: 20201, usage: "occasional" },
            { period: 20194, usage: "occasional" },
        ]
    },
    {
        name: "Windows Presentation Foundation (WPF)",
        colour: "BA55D3",
        parentid: ".net",
        history: [
            { period: 20203, usage: "occasional" },
            { period: 20202, usage: "occasional" },
            { period: 20201, usage: "occasional" },
            { period: 20194, usage: "occasional" },
            { period: 20173, usage: "primary" },
            { period: 20172, usage: "primary" },
            { period: 20171, usage: "primary" },
            { period: 20164, usage: "primary" },
            { period: 20163, usage: "primary" },
            { period: 20162, usage: "primary" },
            { period: 20161, usage: "primary" },
            { period: 20154, usage: "primary" },
            { period: 20153, usage: "primary" },
            { period: 20152, usage: "primary" },
            { period: 20151, usage: "primary" },
            { period: 20144, usage: "primary" },
            { period: 20143, usage: "primary" },
            { period: 20142, usage: "primary" },
            { period: 20141, usage: "primary" },
            { period: 20134, usage: "primary" },
            { period: 20133, usage: "primary" },
            { period: 20132, usage: "primary" },
            { period: 20131, usage: "primary" },
            { period: 20124, usage: "primary" },
            { period: 20123, usage: "primary" },
            { period: 20122, usage: "regular" },
            { period: 20093, usage: "primary" },
            { period: 20092, usage: "primary" },
            { period: 20091, usage: "primary" },
            { period: 20084, usage: "primary" },
            { period: 20083, usage: "primary" },
        ]
    },
    {
        name: "Entity Framework",
        colour: "9400D3",
        parentid: ".net",
        history: [
            { period: 20173, usage: "primary" },
            { period: 20172, usage: "primary" },
            { period: 20171, usage: "primary" },
            { period: 20164, usage: "primary" },
            { period: 20163, usage: "primary" },
            { period: 20162, usage: "primary" },
            { period: 20161, usage: "primary" },
            { period: 20154, usage: "primary" },
            { period: 20153, usage: "primary" },
            { period: 20152, usage: "primary" },
            { period: 20151, usage: "primary" },
            { period: 20144, usage: "primary" },
            { period: 20143, usage: "primary" },
            { period: 20142, usage: "primary" },
            { period: 20141, usage: "primary" },
            { period: 20134, usage: "primary" },
            { period: 20133, usage: "primary" },
            { period: 20132, usage: "primary" },
            { period: 20131, usage: "primary" },
            { period: 20124, usage: "primary" },
            { period: 20123, usage: "primary" },
            { period: 20122, usage: "regular" },
            { period: 20104, usage: "primary" },
            { period: 20103, usage: "primary" },
            { period: 20102, usage: "primary" },
            { period: 20101, usage: "primary" },
        ]
    },
    {
        name: "ADO.NET",
        colour: "9932CC",
        parentid: ".net",
        history: [
            { period: 20081, usage: "primary" },
            { period: 20074, usage: "primary" },
            { period: 20073, usage: "primary" },
            { period: 20072, usage: "primary" },
            { period: 20071, usage: "primary" },
            { period: 20064, usage: "primary" },
            { period: 20063, usage: "primary" },
            { period: 20062, usage: "primary" },
            { period: 20061, usage: "primary" },
            { period: 20054, usage: "primary" },
            { period: 20053, usage: "primary" },
            { period: 20052, usage: "primary" }
        ]
    },
    {
        name: "Windows Communication Foundation (WCF)",
        colour: "8A2BE2",
        parentid: [".net", "webdev"],
        history: [
            { period: 20104, usage: "primary" },
            { period: 20103, usage: "primary" },
            { period: 20102, usage: "primary" },
            { period: 20101, usage: "primary" },
        ]
    },
    {
        name: "Silverlight",
        colour: "9370DB",
        parentid: [".net", "webdev"],
        history: [
            { period: 20113, usage: "occasional" },
            { period: 20112, usage: "occasional" },
            { period: 20111, usage: "occasional" },
            { period: 20104, usage: "occasional" },
            { period: 20103, usage: "occasional" },
            { period: 20102, usage: "primary" },
            { period: 20101, usage: "primary" },
            { period: 20094, usage: "primary" },
            { period: 20082, usage: "primary" },
            { period: 20081, usage: "primary" },
            { period: 20074, usage: "primary" },
        ]
    },
    {
        name: ".NET Remoting",
        colour: "E6E6FA",
        parentid: ".net",
        history: [
            { period: 20051, usage: "primary" },
            { period: 20044, usage: "primary" },
            { period: 20043, usage: "primary" },
            { period: 20042, usage: "primary" },
            { period: 20041, usage: "primary" },
            { period: 20034, usage: "primary" },
            { period: 20033, usage: "primary" },
            { period: 20032, usage: "primary" },
            { period: 20031, usage: "primary" },
            { period: 20024, usage: "primary" },
            { period: 20023, usage: "primary" },
            { period: 20022, usage: "primary" },
            { period: 20021, usage: "primary" },
        ]
    },
    {
        name: "C/C++",
        colour: "78ccf0",
        history: [
            { period: 20203, usage: "regular" },
            { period: 20202, usage: "regular" },
            { period: 20201, usage: "regular" },
            { period: 20194, usage: "regular" },
            { period: 20193, usage: "primary" },
            { period: 20192, usage: "primary" },
            { period: 20191, usage: "primary" },
            { period: 20184, usage: "primary" },
            { period: 20183, usage: "primary" },
            { period: 20182, usage: "primary" },
            { period: 20181, usage: "primary" },
            { period: 20174, usage: "primary" },
            { period: 20173, usage: "regular" },
            { period: 20172, usage: "regular" },
            { period: 20171, usage: "regular" },
            { period: 20164, usage: "primary" },
            { period: 20163, usage: "primary" },
            { period: 20162, usage: "primary" },
            { period: 20161, usage: "primary" },
            { period: 20154, usage: "primary" },
            { period: 20153, usage: "primary" },
            { period: 20152, usage: "primary" },
            { period: 20151, usage: "primary" },
            { period: 20144, usage: "primary" },
            { period: 20143, usage: "primary" },
            { period: 20142, usage: "primary" },
            { period: 20141, usage: "primary" },
            { period: 20134, usage: "primary" },
            { period: 20133, usage: "primary" },
            { period: 20132, usage: "primary" },
            { period: 20131, usage: "primary" },
            { period: 20164, usage: "regular" },
            { period: 20093, usage: "primary" },
            { period: 20092, usage: "primary" },
            { period: 20091, usage: "primary" },
            { period: 20084, usage: "primary" },
            { period: 20083, usage: "primary" },
        ]
    },
    {
        name: "Dev Lead/Management",
        description: "Management and leadership",
        colour: "990099",
        history: [
            { period: 20193, usage: "occasional" },
            { period: 20192, usage: "occasional" },
            { period: 20191, usage: "occasional" },
            { period: 20184, usage: "occasional" },
            { period: 20183, usage: "occasional" },
            { period: 20182, usage: "occasional" },
            { period: 20181, usage: "occasional" },
            { period: 20174, usage: "occasional" },
            { period: 20173, usage: "primary" },
            { period: 20172, usage: "primary" },
            { period: 20171, usage: "primary" },
            { period: 20164, usage: "primary" },
            { period: 20163, usage: "primary" },
            { period: 20162, usage: "primary" },
            { period: 20161, usage: "primary" },
            { period: 20154, usage: "primary" },
            { period: 20153, usage: "primary" },
            { period: 20152, usage: "primary" },
            { period: 20151, usage: "primary" },
            { period: 20144, usage: "primary" },
            { period: 20143, usage: "primary" },
            { period: 20142, usage: "primary" },
            { period: 20141, usage: "primary" },
            { period: 20134, usage: "primary" },
            { period: 20133, usage: "primary" },
            { period: 20132, usage: "primary" },
            { period: 20131, usage: "primary" },
            { period: 20124, usage: "primary" },
            { period: 20123, usage: "primary" },
            { period: 20122, usage: "primary" },
            { period: 20121, usage: "primary" },
            { period: 20114, usage: "primary" },
            { period: 20113, usage: "primary" },
            { period: 20081, usage: "primary" },
            { period: 20074, usage: "primary" },
            { period: 20073, usage: "primary" },
            { period: 20072, usage: "primary" },
            { period: 20071, usage: "primary" },
            { period: 20064, usage: "primary" },
            { period: 20063, usage: "primary" },
            { period: 20062, usage: "primary" },
            { period: 20061, usage: "primary" },
            { period: 20054, usage: "primary" },
            { period: 20053, usage: "primary" },
            { period: 20052, usage: "primary" },
        ]
    },
    {
        name: "Real-time Comms",
        id: "rtc",
        description: "Real-time communications, including audio and video streaming.",
        colour: "f26722",
        history: [
            { period: 20203, usage: "primary" },
            { period: 20202, usage: "primary" },
            { period: 20201, usage: "primary" },
            { period: 20194, usage: "primary" },
            { period: 20174, usage: "occasional" },
            { period: 20173, usage: "occasional" },
            { period: 20172, usage: "occasional" },
            { period: 20171, usage: "occasional" },
            { period: 20164, usage: "occasional" },
            { period: 20163, usage: "occasional" },
            { period: 20162, usage: "occasional" },
            { period: 20161, usage: "occasional" },
            { period: 20154, usage: "occasional" },
            { period: 20153, usage: "occasional" },
            { period: 20152, usage: "occasional" },
            { period: 20151, usage: "occasional" },
            { period: 20144, usage: "occasional" },
            { period: 20143, usage: "occasional" },
            { period: 20142, usage: "occasional" },
            { period: 20141, usage: "occasional" },
            { period: 20134, usage: "occasional" },
            { period: 20133, usage: "occasional" },
            { period: 20132, usage: "occasional" },
            { period: 20131, usage: "occasional" },
            { period: 20102, usage: "primary" },
            { period: 20101, usage: "primary" },
            { period: 20094, usage: "primary" },
            { period: 20081, usage: "primary" },
            { period: 20074, usage: "primary" },
            { period: 20073, usage: "primary" },
            { period: 20072, usage: "primary" },
            { period: 20071, usage: "primary" },
            { period: 20064, usage: "primary" },
            { period: 20063, usage: "primary" },
            { period: 20062, usage: "primary" },
            { period: 20061, usage: "primary" },
            { period: 20054, usage: "primary" },
            { period: 20053, usage: "primary" },
            { period: 20052, usage: "primary" },
        ]
    },
    {
        name: "SIP/VoIP",
        parentid: "rtc",
        colour: "FF7F50",
        history: [
            { period: 20203, usage: "primary" },
            { period: 20202, usage: "primary" },
            { period: 20201, usage: "primary" },
            { period: 20194, usage: "primary" },
            { period: 20102, usage: "primary" },
            { period: 20101, usage: "primary" },
            { period: 20081, usage: "primary" },
            { period: 20074, usage: "primary" },
            { period: 20073, usage: "primary" },
            { period: 20072, usage: "primary" },
            { period: 20071, usage: "primary" },
            { period: 20064, usage: "primary" },
            { period: 20063, usage: "primary" },
            { period: 20062, usage: "primary" },
            { period: 20061, usage: "primary" },
            { period: 20054, usage: "primary" },
            { period: 20053, usage: "primary" },
            { period: 20052, usage: "primary" },
        ]
    },
    {
        name: "Asterisk",
        parentid: "rtc",
        colour: "FF4500",
        history: [
            { period: 20081, usage: "primary" },
            { period: 20074, usage: "primary" },
            { period: 20073, usage: "primary" },
            { period: 20081, usage: "primary" },
            { period: 20074, usage: "primary" },
            { period: 20073, usage: "primary" },
            { period: 20072, usage: "primary" },
            { period: 20071, usage: "primary" },
            { period: 20064, usage: "primary" },
            { period: 20063, usage: "primary" },
            { period: 20062, usage: "primary" },
            { period: 20061, usage: "primary" },
            { period: 20054, usage: "primary" },
            { period: 20053, usage: "primary" },
            { period: 20052, usage: "primary" },
            { period: 20051, usage: "primary" },
            { period: 20044, usage: "primary" },
            { period: 20043, usage: "primary" },
            { period: 20042, usage: "primary" },
            { period: 20041, usage: "primary" },
        ]
    },
    {
        name: "WebRTC",
        parentid: "rtc",
        colour: "FF6347",
        history: [
            { period: 20203, usage: "primary" },
            { period: 20202, usage: "primary" },
            { period: 20201, usage: "primary" },
            { period: 20194, usage: "primary" },
            { period: 20174, usage: "occasional" },
            { period: 20173, usage: "occasional" },
            { period: 20172, usage: "occasional" },
            { period: 20171, usage: "occasional" },
            { period: 20164, usage: "occasional" },
            { period: 20163, usage: "occasional" },
            { period: 20162, usage: "occasional" },
            { period: 20161, usage: "occasional" },
            { period: 20154, usage: "occasional" },
            { period: 20153, usage: "occasional" },
            { period: 20152, usage: "occasional" },
            { period: 20151, usage: "occasional" },
            { period: 20144, usage: "occasional" },
            { period: 20143, usage: "occasional" },
            { period: 20142, usage: "occasional" },
            { period: 20141, usage: "occasional" },
            { period: 20134, usage: "occasional" },
            { period: 20133, usage: "occasional" },
            { period: 20132, usage: "occasional" },
            { period: 20131, usage: "occasional" },
        ]
    },
    {
        name: "Web Development",
        id: "webdev",
        description: "Technologies related to front end web applications",
        colour: "B0E0E6",
        history: [
            { period: 20012, usage: "primary" },
            { period: 20011, usage: "primary" },
            { period: 20004, usage: "primary" },
            { period: 19992, usage: "regular" },
            { period: 19991, usage: "regular" },
        ]
    },
    {
        name: "Microsoft Active Server Pages (ASP)",
        parentid: "webdev",
        colour: "ADD8E6",
        history: [
            { period: 20002, usage: "regular" },
            { period: 20001, usage: "regular" },
        ]
    },
    {
        name: "Javascript",
        parentid: "webdev",
        colour: "ADD8E6",
        history: [
            { period: 20012, usage: "primary" },
            { period: 20011, usage: "primary" },
        ]
    },
    {
        name: "WordPress",
        parentid: "webdev",
        colour: "87CEFA",
        history: [
            { period: 20132, usage: "regular" },
            { period: 20131, usage: "regular" },
        ]
    },
    {
        name: "Database Development",
        id: "rdbms",
        description: "Relational Database Managements Systems",
        colour: "7CFC00",
        history: [
            { period: 20174, usage: "primary" },
            { period: 20173, usage: "primary" },
            { period: 20172, usage: "primary" },
            { period: 20171, usage: "primary" },
            { period: 20164, usage: "primary" },
            { period: 20163, usage: "primary" },
            { period: 20162, usage: "primary" },
            { period: 20161, usage: "primary" },
            { period: 20154, usage: "primary" },
            { period: 20153, usage: "primary" },
            { period: 20152, usage: "primary" },
            { period: 20151, usage: "primary" },
            { period: 20144, usage: "primary" },
            { period: 20143, usage: "primary" },
            { period: 20142, usage: "primary" },
            { period: 20141, usage: "primary" },
            { period: 20134, usage: "primary" },
            { period: 20133, usage: "primary" },
            { period: 20132, usage: "primary" },
            { period: 20131, usage: "primary" },
            { period: 20124, usage: "primary" },
            { period: 20123, usage: "primary" },
            { period: 20122, usage: "primary" },
            { period: 20113, usage: "primary" },
            { period: 20112, usage: "primary" },
            { period: 20111, usage: "primary" },
            { period: 20104, usage: "primary" },
            { period: 20103, usage: "primary" },
            { period: 20094, usage: "primary" },
            { period: 20081, usage: "primary" },
            { period: 20074, usage: "primary" },
            { period: 20073, usage: "primary" },
            { period: 20072, usage: "primary" },
            { period: 20071, usage: "primary" },
            { period: 20064, usage: "primary" },
            { period: 20063, usage: "primary" },
            { period: 20062, usage: "primary" },
            { period: 20061, usage: "primary" },
            { period: 20054, usage: "primary" },
            { period: 20053, usage: "primary" },
            { period: 20052, usage: "primary" },
        ]
    },
    {
        name: "PostgreSQL",
        parentid: "rdbms",
        colour: "7FFF00",
        history: [
            { period: 20094, usage: "primary" },
            { period: 20081, usage: "primary" },
            { period: 20074, usage: "primary" },
            { period: 20073, usage: "primary" },
            { period: 20072, usage: "primary" },
            { period: 20071, usage: "primary" },
            { period: 20064, usage: "primary" },
            { period: 20063, usage: "primary" },
            { period: 20062, usage: "primary" },
            { period: 20061, usage: "primary" },
            { period: 20054, usage: "primary" },
            { period: 20053, usage: "primary" },
            { period: 20052, usage: "primary" },
        ]
    },
    {
        name: "MySQL",
        parentid: "rdbms",
        colour: "32CD32",
        history: [
            { period: 20152, usage: "primary" },
            { period: 20151, usage: "primary" },
            { period: 20144, usage: "primary" },
            { period: 20143, usage: "primary" },
            { period: 20142, usage: "primary" },
            { period: 20141, usage: "primary" },
            { period: 20134, usage: "primary" },
            { period: 20133, usage: "primary" },
            { period: 20132, usage: "primary" },
            { period: 20131, usage: "primary" },
            { period: 20124, usage: "primary" },
            { period: 20123, usage: "primary" },
            { period: 20122, usage: "primary" },
        ]
    },
    {
        name: "Microsoft SQL Server",
        parentid: "rdbms",
        colour: "00FF00",
        history: [
            { period: 20173, usage: "primary" },
            { period: 20172, usage: "primary" },
            { period: 20171, usage: "primary" },
            { period: 20164, usage: "primary" },
            { period: 20163, usage: "primary" },
            { period: 20162, usage: "primary" },
            { period: 20161, usage: "primary" },
            { period: 20154, usage: "primary" },
            { period: 20153, usage: "primary" },
            { period: 20152, usage: "primary" },
            { period: 20113, usage: "primary" },
            { period: 20112, usage: "primary" },
            { period: 20111, usage: "primary" },
            { period: 20104, usage: "primary" },
            { period: 20103, usage: "primary" },
        ]
    },
    {
        name: "Microsoft SSIS Server",
        parentid: "rdbms",
        colour: "228B22",
        history: [
            { period: 20173, usage: "primary" },
            { period: 20172, usage: "primary" },
            { period: 20171, usage: "primary" },
            { period: 20164, usage: "primary" },
            { period: 20163, usage: "primary" },
            { period: 20162, usage: "primary" },
            { period: 20161, usage: "primary" }
        ]
    },
    {
        name: "Other",
        id: "other",
        description: "Other technologies or programming languages.",
        colour: "C0C0C0",
        history: [ ]
    },
    {
        name: "Perl",
        parentid: "other",
        colour: "2F4F4F",
        history: [
            { period: 19994, usage: "regular" },
            { period: 19993, usage: "regular" },
        ]
    },
    {
        name: "VBScript Automation",
        parentid: "other",
        colour: "696969",
        history: [
            { period: 20022, usage: "primary" },
            { period: 20021, usage: "primary" },
            { period: 20014, usage: "primary" },
            { period: 20011, usage: "primary" },
            { period: 20004, usage: "primary" },
            { period: 20003, usage: "primary" }
        ]
    },
    {
        name: "Microsoft Media Foundation",
        parentid: "other",
        colour: "708090",
        history: [
            { period: 20203, usage: "regular" },
            { period: 20201, usage: "regular" },
            { period: 20194, usage: "regular" },
            { period: 20153, usage: "regular" },
            { period: 20152, usage: "regular" }
        ]
    },
    {
        name: "iOS/Objective-C Development",
        colour: "000000",
        parentid: "other",
        history: [
            { period: 20173, usage: "occasional" },
            { period: 20172, usage: "occasional" },
            { period: 20171, usage: "occasional" },
            { period: 20164, usage: "occasional" },
            { period: 20163, usage: "occasional" },
            { period: 20162, usage: "occasional" },
            { period: 20161, usage: "occasional" },
            { period: 20154, usage: "occasional" },
            { period: 20153, usage: "occasional" },
            { period: 20152, usage: "occasional" },
            { period: 20151, usage: "occasional" },
            { period: 20144, usage: "occasional" },
            { period: 20143, usage: "occasional" },
            { period: 20142, usage: "occasional" },
            { period: 20141, usage: "occasional" },
            { period: 20134, usage: "occasional" },
            { period: 20133, usage: "occasional" },
            { period: 20132, usage: "occasional" },
            { period: 20131, usage: "occasional" },
            { period: 20124, usage: "regular" },
            { period: 20123, usage: "regular" },
            { period: 20122, usage: "regular" },
            { period: 20121, usage: "primary" },
            { period: 20114, usage: "primary" }
        ]
    },
    {
        name: "Blockchain",
        colour: "A9A9A9",
        parentid: "other",
        history: [
            { period: 20193, usage: "primary" },
            { period: 20192, usage: "primary" },
            { period: 20191, usage: "primary" },
            { period: 20184, usage: "primary" },
            { period: 20183, usage: "primary" },
            { period: 20182, usage: "primary" },
            { period: 20181, usage: "primary" },
            { period: 20174, usage: "primary" }
        ]
    },
    {
        name: "Network/Socket Development",
        description: "Networking",
        parentid: "other",
        colour: "778899",
        history: [
            { period: 20203, usage: "primary" },
            { period: 20202, usage: "primary" },
            { period: 20201, usage: "primary" },
            { period: 20194, usage: "primary" },
            { period: 20193, usage: "primary" },
            { period: 20192, usage: "primary" },
            { period: 20191, usage: "primary" },
            { period: 20184, usage: "primary" },
            { period: 20183, usage: "primary" },
            { period: 20182, usage: "primary" },
            { period: 20181, usage: "primary" },
            { period: 20174, usage: "primary" },
            { period: 20102, usage: "primary" },
            { period: 20101, usage: "primary" },
            { period: 20094, usage: "primary" },
            { period: 20074, usage: "primary" },
            { period: 20073, usage: "primary" },
            { period: 20081, usage: "primary" },
            { period: 20074, usage: "primary" },
            { period: 20073, usage: "primary" },
            { period: 20072, usage: "primary" },
            { period: 20071, usage: "primary" },
            { period: 20064, usage: "primary" },
            { period: 20063, usage: "primary" },
            { period: 20062, usage: "primary" },
            { period: 20061, usage: "primary" },
            { period: 20054, usage: "primary" },
            { period: 20053, usage: "primary" },
            { period: 20052, usage: "primary" },
        ]
    },
];